### ISSUE TITLE
Add support for dynamically changing channel

### ISSUE THREAD

**Issue by ngregrichardson** [talk2MeGooseman/react-twitch-embed-video#5]
I had assumed this was possible, and maybe I'm doing something wrong, but updating the props for the component. This is what I'm doing:

```
<ReactTwitchEmbedVideo channel={this.state.webcast.channel} layout="video" />
```
My state is changing, but the channel won't change in the TwitchEmbed component. I even added this to your index.js just in case:
```
key: "componentWillReceiveProps",
value: function(nextProps) {
  if (nextProps.channel !== this.props.channel) {
    this.setState({ channel: nextProps.channel });
    this.componentDidMount();
  }
},
```

Any suggestions?

**Comment by talk2MeGooseman** [comment]
Hey @ngregrichardson not sure why I am not getting notified about issues being filed, I think the issue lies with the iframe that renders. I'll try looking into this issue but my best guess right now is that the video iframe needs to be completed destroyed and rerendered again to use the new channel value

**Comment by talk2MeGooseman** [comment]
This feature will be coming up in 1.1.0 release
